owner: MinerXO # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
#runner: "[self-hosted, linux]"
sites:
  - name: PW-Manager
    url: $MBIT
  - name: PW-Simon
    url: $SBIT
  - name: Joseph
    url: $ITM
  - name: 1blu
    url: $ONEBLU
    check: "tcp-ping"
    port: 443
#  - name: Test Broken Site
#    url: https://thissitedoesnotexist.koj.co
#  - name: IPv6 test
#    url: forwardemail.net
#    port: 80
#    check: "tcp-ping"
#    ipv6: true
assignees:
  - MinerXO
status-website:
  theme: night
  robotsText: "User-agent: * \n Disallow: /"
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime Website
#  introTitle: "**Upptime3** is the open-source uptime monitor and status page, powered entirely by GitHub."
#  introMessage: 4This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
#   schedule:
#    - cron: "2-58/5 * * * 2,4,6"
#    - cron: "2-58/5 0-2,4-23 * * 1,3,5,0"

workflowSchedule:
  uptime: "2-57/5 0-2,4-23 * * *"

#skipDescriptionUpdate: true
#skipTopicsUpdate: false
#skipHomepageUpdate: true
i18n:
  url: "URL"
  status: "Status"
  history: "Verlauf"
  responseTimeLabel: "Antwortzeit" # Eindeutiger Schlüssel
  uptimeLabel: "Verfügbarkeit" # Umbenannt, um doppelten Schlüssel zu vermeiden
  responseTimeGraphAlt: "Antwortzeit-Diagramm"
  ms: "ms"
  responseTimeDay: "Antwortzeit der letzten 24 Stunden"
  responseTimeWeek: "Antwortzeit der letzten 7 Tage"
  responseTimeMonth: "Antwortzeit der letzten 30 Tage"
  responseTimeYear: "Antwortzeit des letzten Jahres"
  allTimeUptime: "Gesamtverfügbarkeit" # Eindeutiger Schlüssel
  uptimeDay: "Verfügbarkeit der letzten 24 Stunden"
  uptimeWeek: "Verfügbarkeit der letzten 7 Tage"
  uptimeMonth: "Verfügbarkeit der letzten 30 Tage"
  uptimeYear: "Verfügbarkeit des letzten Jahres"
  allSystemsOperational: "🟩 Alle Systeme betriebsbereit"
  degradedPerformance: "🟨 Eingeschränkte Leistung"
  completeOutage: "🟥 Totalausfall"
  partialOutage: "🟧 Teilausfall"
  up: "🟩"
  down: "🟥"
  degraded: "🟧"
